services:
  # always have shade-agent-api first in order of services
  shade-agent-api:
    environment:
      NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
      NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
      API_CODEHASH: ${API_CODEHASH}
      APP_CODEHASH: ${APP_CODEHASH}
      NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
      NEAR_RPC_URL: ${NEAR_RPC_URL}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      AGENT_ACCOUNT_ID: ${AGENT_ACCOUNT_ID}
      VOTING_CONTRACT_ID: ${VOTING_CONTRACT_ID}
    platform: linux/amd64 # Explicitly set for TDX
    # shade-agent-api-image
    image: mattdlockyer/shade-agent-api@sha256:a86e3a4300b069c08d629a38d61a3d780f7992eaf36aa505e4527e466553e2e5
    container_name: shade-agent-api
    # DO NOT EXPOSE THE API PORT TO THE PUBLIC
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
  shade-agent-app:
    environment:
      NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    platform: linux/amd64 # Explicitly set for TDX
    # shade-agent-app-image
    image: jwaup/votron@sha256:2a2f4704345359172f31e992188c60c2cbff4c2151dceeabccf472bad8031243
    container_name: shade-agent-app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
