services:
    # always have shade-agent-api first in order of services
    shade-agent-api:
        environment:
            NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
            NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
            API_CODEHASH: ${API_CODEHASH}
            APP_CODEHASH: ${APP_CODEHASH}
            ENTROPY: ${ENTROPY}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            SHADE_AGENT_PORT: ${SHADE_AGENT_PORT}
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-api-image
        image: mattdlockyer/shade-agent-api@sha256:3858c9828e510671d1bc0975d3853087b0aa859260e4c1c7e8b068e57bc0fe70
        container_name: shade-agent-api
        ports:
            - '3140:3140'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
    my-app:
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-app-image
        image: pivortex/my-app@sha256:d9e50a5c160a0dd580842e7f753f25bc83235f4d2b127d250356cae75b152914
        container_name: my-app
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
