services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/shade-agent-template:latest@sha256:cd8a76702a3949b31a34333cc3c80f6bfbe0874d301fa8f030eebc1b4d264d9c
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
